package eu.kanade.tachiyomi.animeextension.id.anichin

import eu.kanade.tachiyomi.animesource.model.AnimeFilter

open class UriPartFilter(
    displayName: String,
    val pairs: Array<Pair<String, String>>,
) : AnimeFilter.Select<String>(displayName, pairs.map { it.first }.toTypedArray()) {
    fun getUriPart() = pairs[state].second
}

class Genre(name: String, val id: String) : AnimeFilter.CheckBox(name)
class GenreList(genres: List<Genre>) : AnimeFilter.Group<Genre>("Genre", genres)

class Season(name: String, val id: String) : AnimeFilter.CheckBox(name)
class SeasonList(seasons: List<Season>) : AnimeFilter.Group<Season>("Season", seasons)

class Studio(name: String, val id: String) : AnimeFilter.CheckBox(name)
class StudioList(studios: List<Studio>) : AnimeFilter.Group<Studio>("Studio", studios)

class StatusFilter :
    UriPartFilter(
        "Status",
        arrayOf(
            Pair("All", ""),
            Pair("Ongoing", "ongoing"),
            Pair("Completed", "completed"),
            Pair("Upcoming", "upcoming"),
            Pair("Hiatus", "hiatus"),
        ),
    )

class TypeFilter :
    UriPartFilter(
        "Type",
        arrayOf(
            Pair("All", ""),
            Pair("Anime", "anime"),
            Pair("OVA", "ova"),
            Pair("Movie", "movie"),
            Pair("Live Action", "live action"),
            Pair("Special", "special"),
            Pair("BD", "bd"),
            Pair("ONA", "ona"),
            Pair("Music", "music"),
            Pair("Donghua", "donghua"),
        ),
    )

class OrderFilter :
    UriPartFilter(
        "Order by",
        arrayOf(
            Pair("Default", ""),
            Pair("A-Z", "title"),
            Pair("Z-A", "titlereverse"),
            Pair("Latest Update", "update"),
            Pair("Latest Added", "latest"),
            Pair("Popular", "popular"),
            Pair("Rating", "rating"),
        ),
    )

object AnichinFilters {
    val GENRES = listOf(
        Genre("Action", "action"),
        Genre("Action Drama", "action-drama"),
        Genre("Actions", "actions"),
        Genre("Adventure", "adventure"),
        Genre("Comedy", "comedy"),
        Genre("Crossdressing", "crossdressing"),
        Genre("Cultivation", "cultivation"),
        Genre("Demons", "demons"),
        Genre("Drama", "drama"),
        Genre("e School", "e-school"),
        Genre("Ecchi", "ecchi"),
        Genre("Fantasy", "fantasy"),
        Genre("Friendship", "friendship"),
        Genre("Game", "game"),
        Genre("Gore", "gore"),
        Genre("Gourmet", "gourmet"),
        Genre("Harem", "harem"),
        Genre("Historical", "historical"),
        Genre("Horror", "horror"),
        Genre("Isekai", "isekai"),
        Genre("Life", "life"),
        Genre("Magic", "magic"),
        Genre("Martial Arts", "martial-arts"),
        Genre("Mecha", "mecha"),
        Genre("Military", "military"),
        Genre("Music", "music"),
        Genre("Mystery", "mystery"),
        Genre("Mythology", "mythology"),
        Genre("Psychological", "psychological"),
        Genre("Reincaranation", "reincaranation"),
        Genre("Reincarnation", "reincarnation"),
        Genre("Romanc", "romanc"),
        Genre("Romance", "romance"),
        Genre("School", "school"),
        Genre("Sci-Fi", "sci-fi"),
        Genre("Shoujo", "shoujo"),
        Genre("Shounen", "shounen"),
        Genre("Slice of Life", "slice-of-life"),
        Genre("Space", "space"),
        Genre("Sports", "sports"),
        Genre("Super Power", "super-power"),
        Genre("Supernatural", "supernatural"),
        Genre("Suspense", "suspense"),
        Genre("Team Sports", "team-sports"),
        Genre("Thriller", "thriller"),
        Genre("Urban Fantasy", "urban-fantasy"),
    )

    val SEASONS = listOf(
        Season("2014", "2014"),
        Season("2015", "2015"),
        Season("2016", "2016"),
        Season("2017", "2017"),
        Season("2018", "2018"),
        Season("2019", "2019"),
        Season("2020", "2020"),
        Season("2021", "2021"),
        Season("2022", "2022"),
        Season("2023", "2023"),
        Season("2024", "2024"),
        Season("2025", "2025"),
        Season("2026", "2026"),
        Season("Spring 2022", "spring-2022"),
        Season("Spring 2023", "spring-2023"),
        Season("Summer 2022", "summer-2022"),
        Season("Summer 2023", "summer-2023"),
        Season("Winter 2023", "winter-2023"),
    )

    val STUDIOS = listOf(
        Studio("2:10 AM Animation", "210-am-animation"),
        Studio("2:10 Animatión", "210-animation"),
        Studio("AHA Entertainment", "aha-entertainment"),
        Studio("ASK Animation Studio", "ask-animation-studio"),
        Studio("Aurora", "aurora"),
        Studio("Axis Studios", "axis-studios"),
        Studio("Azure Sea Studios", "azure-sea-studios"),
        Studio("B.CMAY PICTURES", "b-cmay-pictures"),
        Studio("Beijing Enlight Pictures", "beijing-enlight-pictures"),
        Studio("BETOBE", "betobe"),
        Studio("Big Firebird Cultural Media", "big-firebird-cultural-media"),
        Studio("Big Firebird Culture", "big-firebird-culture"),
        Studio("BigBigSun", "bigbigsun"),
        Studio("Bilibili", "bilibili"),
        Studio("BlueArc Animation Studio", "bluearc-animation-studio"),
        Studio("Borutong", "borutong"),
        Studio("Boyan Pictures", "boyan-pictures"),
        Studio("BUILD DREAM", "build-dream"),
        Studio("BYMENT", "byment"),
        Studio("CG Year", "cg-year"),
        Studio("Chongzhuo Animation", "chongzhuo-animation"),
        Studio("Chosen", "chosen"),
        Studio("Chosen Studio", "chosen-studio"),
        Studio("Cloud Art", "cloud-art"),
        Studio("Cloud Culture", "cloud-culture"),
        Studio("CMC Media", "cmc-media"),
        Studio("Coastline Animation Studio", "coastline-animation-studio"),
        Studio("Colored Pencil Animation", "colored-pencil-animation"),
        Studio("Colored-Pencil Animation Design", "colored-pencil-animation-design"),
        Studio("D.ROCK-ART", "d-rock-art"),
        Studio("Da Yu", "da-yu"),
        Studio("Dancing CG Studio", "dancing-cg-studio"),
        Studio("Dangun Pictures", "dangun-pictures"),
        Studio("DC Entertainment", "dc-entertainment"),
        Studio("DC Impression Vision", "dc-impression-vision"),
        Studio("Djinn Power", "djinn-power"),
        Studio("EMT Squared", "emt-squared"),
        Studio("Escape Velocity Animation", "escape-velocity-animation"),
        Studio("Fengyun Animation", "fengyun-animation"),
        Studio("Flying Fish Studio", "flying-fish-studio"),
        Studio("Foch Film", "foch-film"),
        Studio("Foch Films", "foch-films"),
        Studio("G.H.Y. Culture & Media", "g-h-y-culture-media"),
        Studio("Garden Culture", "garden-culture"),
        Studio("Green Planet Studio", "green-planet-studio"),
        Studio("Guangzhou Liu Ling Yi", "guangzhou-liu-ling-yi"),
        Studio("Haoliners Animation League", "haoliners-animation-league"),
        Studio("He Zhou Culture", "he-zhou-culture"),
        Studio("Heart & Soul Animation", "heart-soul-animation"),
        Studio("High Energy Studio", "high-energy-studio"),
        Studio("HM Heros", "hm-heros"),
        Studio("Honglu Technology", "honglu-technology"),
        Studio("Hua Dream", "hua-dream"),
        Studio("iQIYI", "iqiyi"),
        Studio("Ji Man Wen Hua", "ji-man-wen-hua"),
        Studio("Joicy Studio", "joicy-studio"),
        Studio("KIO STUDIO", "kio-studio"),
        Studio("KJJ Animation", "kjj-animation"),
        Studio("Kunjing Culture", "kunjing-culture"),
        Studio("L²Studio", "l%c2%b2studio"),
        Studio("LAN Studio", "lan-studio"),
        Studio("Left Pocket Studio", "left-pocket-studio"),
        Studio("LIDENFILMS", "lidenfilms"),
        Studio("Light Chaser Animation Studios", "light-chaser-animation-studios"),
        Studio("Liliyabi Company Introduction", "liliyabi-company-introduction"),
        Studio("Lingsanwu Animation", "lingsanwu-animation"),
        Studio("Liyu Culture", "liyu-culture"),
        Studio("Long Zhi Gu Wenhua", "long-zhi-gu-wenhua"),
        Studio("Lx Animation Studio", "lx-animation-studio"),
        Studio("Majestic Studio", "majestic-studio"),
        Studio("Mandrill Picture Corp", "mandrill-picture-corp"),
        Studio("Martial Arts Reincaranation", "martial-arts-reincaranation"),
        Studio("Medo", "medo"),
        Studio("Midway Games", "midway-games"),
        Studio("Mili Digital", "mili-digital"),
        Studio("Mili Pictures", "mili-pictures"),
        Studio("Mokai Technology", "mokai-technology"),
        Studio("Motion Magic", "motion-magic"),
        Studio("Namu Animation", "namu-animation"),
        Studio("October Media", "october-media"),
        Studio("Oriental Creative Color", "oriental-creative-color"),
        Studio("Original Force", "original-force"),
        Studio("Painted Edge", "painted-edge"),
        Studio("Paper Plane Animation Studio", "paper-plane-animation-studio"),
        Studio("Passion Paint Animation", "passion-paint-animation"),
        Studio("Pb Animation Co. Ltd.", "pb-animation-co-ltd"),
        Studio("Phantom", "phantom"),
        Studio("Qing Xiang", "qing-xiang"),
        Studio("Qingxiang Culture", "qingxiang-culture"),
        Studio("Qiyuan Yinghua", "qiyuan-yinghua"),
        Studio("Quyue Technology", "quyue-technology"),
        Studio("Red Dog Culture House", "red-dog-culture-house"),
        Studio("Rocen", "rocen"),
        Studio("Ruo Hong Culture", "ruo-hong-culture"),
        Studio("Shanghai Foch Film", "shanghai-foch-film"),
        Studio("Shanghai Foch Film Culture Investment", "shanghai-foch-film-culture-investment"),
        Studio("Shanghai Motion Magic", "shanghai-motion-magic"),
        Studio("Sharefun Studio", "sharefun-studio"),
        Studio("Shengying Animation", "shengying-animation"),
        Studio("Shenman Entertainment", "shenman-entertainment"),
        Studio("Shenying Animation", "shenying-animation"),
        Studio("SJYNEXCUS", "sjynexcus"),
        Studio("Skyloong", "skyloong"),
        Studio("Soda Bear Animation", "soda-bear-animation"),
        Studio("Soyep", "soyep"),
        Studio("Sparkly Key Animation Studio", "sparkly-key-animation-studio"),
        Studio("Star Hunter Animation", "star-hunter-animation"),
        Studio("Studio Goindol", "studio-goindol"),
        Studio("Studio LAN", "studio-lan"),
        Studio("Success Corp.", "success-corp"),
        Studio("Suoyi Technology", "suoyi-technology"),
        Studio("Taikong Works", "taikong-works"),
        Studio("Tang Kirin Culture", "tang-kirin-culture"),
        Studio("Three Realms Animation", "three-realms-animation"),
        Studio("Thundray", "thundray"),
        Studio("Tong Ming Xuan", "tong-ming-xuan"),
        Studio("Transcendence Picture", "transcendence-picture"),
        Studio("TrioPen Studio", "triopen-studio"),
        Studio("UKA", "uka"),
        Studio("Warner Bros. Animation", "warner-bros-animation"),
        Studio("Wawayu Animation", "wawayu-animation"),
        Studio("Wonder Cat Animation", "wonder-cat-animation"),
        Studio("Wu Zhi Guanying Dongman", "wu-zhi-guanying-dongman"),
        Studio("Xiaoming Taiji", "xiaoming-taiji"),
        Studio("Xing Yi Kai Chen", "xing-yi-kai-chen"),
        Studio("XMOV", "xmov"),
        Studio("Xuan Yuan", "xuan-yuan"),
        Studio("Xuni Pictures", "xuni-pictures"),
        Studio("Xuni Ying Ye", "xuni-ying-ye"),
        Studio("Year Young Culture", "year-young-culture"),
        Studio("YHKT Entertainment", "yhkt-entertainment"),
        Studio("Yi Chen Animation", "yi-chen-animation"),
        Studio("Yien Animation Studio", "yien-animation-studio"),
        Studio("Yofox Culture", "yofox-culture"),
        Studio("Yosep", "yosep"),
    )
}
