name: Build Xvideos Only

on:
  push:
    branches:
      - master
    paths:
      - 'src/all/xvideos/**'  # Sesuaikan dengan path modul Xvideos Anda
      - 'build.gradle'
      - '.github/workflows/build_push.yml'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Xvideos Extension
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout ${{ github.ref_name }} branch
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare signing key
        if: env.HAS_SIGNING_KEY == 'true'
        env:
          HAS_SIGNING_KEY: ${{ secrets.SIGNING_KEY != '' }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" | base64 -d > signingkey.jks
          chmod 600 signingkey.jks

      - name: Build Xvideos APK
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # Mem-build APK khusus untuk modul Xvideos
          ./gradlew :src:all:xvideos:spotlessApply
          ./gradlew :src:all:xvideos:assembleRelease

      - name: Upload Xvideos APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Xvideos-APK"
          path: "src/all/xvideos/build/outputs/apk/release/*.apk"
          retention-days: 7

      - name: Clean up CI files
        if: always()
        run: rm -f signingkey.jks
