name: Generate Android Keystore

on:
  workflow_dispatch:
    inputs:
      keystore_name:
        description: "Nama file keystore"
        required: true
        default: "signingkey.jks"

      alias:
        description: "Alias key"
        required: true
        default: "release"

      store_password:
        description: "Keystore password"
        required: true

      key_password:
        description: "Key password"
        required: true

      common_name:
        description: "Common Name (CN)"
        required: false
        default: "Developer"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -keystore "${{ github.event.inputs.keystore_name }}" \
            -alias "${{ github.event.inputs.alias }}" \
            -storepass "${{ github.event.inputs.store_password }}" \
            -keypass "${{ github.event.inputs.key_password }}" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=${{ github.event.inputs.common_name }}, OU=Developer, O=Personal, L=Unknown, ST=Unknown, C=ID"

      - name: Encode Base64
        run: |
          base64 -w 0 "${{ github.event.inputs.keystore_name }}" > signingkey.base64

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: android-keystore
          path: |
            ${{ github.event.inputs.keystore_name }}
            signingkey.base64
